apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx-deployment
  labels:
    app: influx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
      - name: influx
        image: influxdb:latest
        ports:
        - containerPort: 8086

---
apiVersion: v1
kind: Service
metadata:
  name: influx-service
spec:
  selector:
    app: influx
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: NodePort
